name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install package (editable) + dev
        run: |
          python -m pip install -U pip
          python -m pip install -e .[dev]

      - name: Pre-commit
        run: pre-commit run -a

      - name: Pytest
        run: pytest -q

      - name: CLI smoke
        run: |
          palpt --help
          palpt --version
          palpt figs --which smoke
